# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "riff_zig-1.0.0-J7H0A7E6TAAFStkejtsMRsIhfgLMLzf5iYxWgeSFBLJu";
    path = fetchzip {
      url = "https://codeload.github.com/haruki7049/RIFF.zig/tar.gz/refs/tags/1.0.0";
      hash = "sha256-ELlLnVXNOfI44m9EbnKAsaWMjDKEAP1i0VnIdv1Tq14=";
    };
  }
]
