# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "riff_zig-1.1.1-J7H0A0lxTADtTCOBj0XmMjnAqTcxr2b31Ba-6ybMtgvP";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/1.1.1.tar.gz";
      hash = "sha256-qycj7jSjZuial7pxy0xvi8S6lgg4neFSpI8VN4+iUtg=";
    };
  }
]
