# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "riff_zig-1.0.0-J7H0AyFyTADI7L_J-tZqbYW-wNLb3vfF-rQmjovWBIkz";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/e07a574b05c7d82a14142a674f825189cf4c40f7.tar.gz";
      hash = "sha256-2UHzG7hSSjLlwAdFNslbx1iZrDsLjlqoihsOLltGyfU=";
    };
  }
]
